global using AutoMapper;
global using Contracts;
global using MassTransit;
global using Microsoft.AspNetCore.Mvc;
global using MongoDB.Driver;
global using MongoDB.Entities;
global using Polly;
global using Polly.Extensions.Http;
global using SearchService.Consumers;
global using SearchService.Data;
global using SearchService.Models;
global using SearchService.Services;
global using static System.Console;