global using AuctionService.Consumers;
global using AuctionService.Data;
global using AuctionService.DTOs;
global using AuctionService.Entities;
global using AutoMapper;
global using Contracts;
global using MassTransit;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using static System.Console;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;